-- Apply only to the independent Speaker database. Never apply to the original team site.
-- Preserve existing authentication accounts and profile approval; remove retired product data.
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='on_auth_user_created' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='current_role' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='is_approved' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='can_coach' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='can_manage_event' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='emit_notification' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='admin_users' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='manage_user' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='set_positions' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='save_post' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='delete_post' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='save_event' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='delete_event' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='save_lineup' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='set_notification_rule' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='mark_notification_read' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='attach_media' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='remove_media' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='snapshot_event_author' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='set_profile_photo' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='claim_volleyball_sync' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='finish_volleyball_sync' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='preserve_imported_match_title' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='neutral_match_venue' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='set_imported_match_title' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='set_volunteer_work_points' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='check_discussion_target' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_discussion' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='save_comment' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='delete_comment' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='set_meme_reaction' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_discussion_counts' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='set_image_settings' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='can_manage_fines' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='save_fine_type' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='save_fine_rules' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='apply_fine' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='cancel_fine' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='get_fines' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='save_fine_multiplier' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='notify_discussion_activity' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='notify_personal_award' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='claim_notification_emails' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='prepare_notification_email' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='finish_notification_email' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='notification_email_status' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='send_test_notification_email' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='set_comment_meme_reaction' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='mark_all_notifications_read' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='set_thread_meme_reaction' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
do $$ declare f record; begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='set_notification_rules' loop execute 'drop function if exists ' || f.signature || ' cascade'; end loop; end $$;
drop table if exists public.comment_meme_reactions cascade;
drop table if exists public.notification_email_queue cascade;
drop table if exists public.registration_requests cascade;
drop table if exists public.fine_multipliers cascade;
drop table if exists public.fines cascade;
drop table if exists public.fine_rules cascade;
drop table if exists public.fine_types cascade;
drop table if exists public.image_settings cascade;
drop table if exists public.meme_reactions cascade;
drop table if exists public.discussion_comments cascade;
drop table if exists public.volunteer_work_points cascade;
drop table if exists public.volleyball_sync_state cascade;
drop table if exists public.profile_photos cascade;
drop table if exists public.notifications cascade;
drop table if exists public.notification_rules cascade;
drop table if exists public.post_media cascade;
drop table if exists public.posts cascade;
drop table if exists public.lineup_revision_slots cascade;
drop table if exists public.lineup_revisions cascade;
drop table if exists public.lineups cascade;
drop table if exists public.volunteer_assignments cascade;
drop table if exists public.match_details cascade;
drop table if exists public.schedule_events cascade;
drop table if exists public.player_positions cascade;
drop table if exists public.player_secondary_roles cascade;
drop table if exists public.player_profiles cascade;

alter table public.profiles add column role text not null default 'user' check(role in ('user','admin'));
update public.profiles set role='admin' where base_role='admin';
alter table public.profiles drop column base_role cascade;
alter table public.profiles rename column full_name to display_name;
drop type if exists public.base_role cascade;
drop type if exists public.secondary_role cascade;
drop type if exists public.volleyball_position cascade;
drop type if exists public.event_type cascade;
drop type if exists public.lineup_role cascade;
-- Buckets are retired only when empty; remove their objects via the Storage API before
-- migrating an existing copy. Never delete storage.objects directly (orphaned blobs).
delete from storage.buckets where id in ('post-images','profile-photos') and not exists(select 1 from storage.objects o where o.bucket_id=storage.buckets.id);
create function public.on_auth_user_created() returns trigger language plpgsql security definer set search_path='' as $$
begin insert into public.profiles(id,display_name) values(new.id,coalesce(nullif(left(new.raw_user_meta_data->>'full_name',100),''),'Speaker')); return new; end $$;
create trigger create_profile after insert on auth.users for each row execute function public.on_auth_user_created();
revoke all on function public.on_auth_user_created() from public,anon,authenticated;
create function public.speaker_access() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.profiles where id=auth.uid() and account_status='approved') $$;
create function public.speaker_admin() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.profiles where id=auth.uid() and account_status='approved' and role='admin') $$;
revoke all on function public.speaker_access(),public.speaker_admin() from public,anon;
grant execute on function public.speaker_access(),public.speaker_admin() to authenticated;
-- Replace remaining profile policies explicitly.
do $$ declare p record; begin for p in select policyname from pg_policies where schemaname='public' and tablename='profiles' loop execute format('drop policy %I on public.profiles',p.policyname); end loop; end $$;
create policy speaker_profile_read on public.profiles for select to authenticated using(id=auth.uid());
revoke all on public.profiles from anon,authenticated;
grant select on public.profiles to authenticated;
